# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a41848a2-3fc5-459b-98e9-f22f3e7e6c10";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2632-8D7E";
      fsType = "vfat";
    };

  fileSystems."/data" = {
    label = "data";
    device = "/dev/sda1";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ddf8cae1-445a-4c7b-82db-3695dd0cf62c"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  networking.hostName = "midgard";
}
