# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6c844301-5503-45d7-b605-482d6c58df2c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ABD3-D9AB";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/3398695c-0375-425c-b3bb-70a48c4021c9"; } ];

  nix.maxJobs = lib.mkDefault 4;

  networking.hostName = "muspelheim";

  fileSystems."/mnt/yelster_public" = {
      device = "//192.168.70.2/public";
      fsType = "cifs";
      options = let
        # this line prevents hanging on network split
        automount_opts = "x-systemd.automount,noauto,x-systemd.idle-timeout=60,x-systemd.device-timeout=5s,x-systemd.mount-timeout=5s";
      in ["${automount_opts},guest,user=nobody,vers=1.0"];
  };
}
